"use client";
import Link from "next/link";
import Image from "next/image";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { signUp } from "@/lib/eunia-api";
import { useSession, userForToken, workspaceForToken } from "@/components/session-provider";
import styles from "../auth.module.css";
export default function SignUpPage() { const router = useRouter(); const { startSession } = useSession(); const [error, setError] = useState(""); const [pending, setPending] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); const firstName = String(form.get("firstName") ?? "").trim(); const lastName = String(form.get("lastName") ?? "").trim(); try { const token = await signUp({ full_name: `${firstName} ${lastName}`.trim(), workspace_name: String(form.get("workspaceName")), email: String(form.get("email")), password: String(form.get("password")) }); const [workspace, user] = await Promise.all([workspaceForToken(token.access_token), userForToken(token.access_token)]); startSession(token.access_token, workspace, user); router.replace("/dashboard"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create your workspace."); } finally { setPending(false); } } return <main className={styles.page}><section className={`${styles.card} ${styles.signupCard}`}><Link className={styles.brand} href="/"><Image className={styles.brandMark} src="/brand/eunia-nia-mark.png" alt="" width={28} height={28} priority />EUNIA</Link><p className={styles.eyebrow}>GET STARTED</p><h1>Create your workspace</h1><p className={styles.subtitle}>Set up a secure home for your AI workforce.</p><form onSubmit={submit}><div className={styles.nameFields}><label>First name<input name="firstName" required minLength={1} autoComplete="given-name" placeholder="Jane" /></label><label>Last name<input name="lastName" required minLength={1} autoComplete="family-name" placeholder="Doe" /></label></div><label>Workspace name<input name="workspaceName" required minLength={2} placeholder="Acme Inc." /></label><label>Work email<input name="email" type="email" required autoComplete="email" placeholder="jane@company.com" /></label><label>Password<input name="password" type="password" minLength={12} required autoComplete="new-password" placeholder="At least 12 characters" /></label>{error && <p className={styles.error}>{error}</p>}<button disabled={pending} type="submit">{pending ? "Creating workspace…" : "Create workspace"}</button></form><p className={styles.switch}>Already have an account? <Link href="/sign-in">Sign in</Link></p></section></main>; }
