"use client";
import Link from "next/link";
import Image from "next/image";
import { usePathname, useRouter } from "next/navigation";
import { useEffect } from "react";
import type { ReactNode } from "react";
import { useSession } from "@/components/session-provider";
import styles from "./workspace-shell.module.css";
type WorkspaceShellProps = { children: ReactNode };
const navigationItems = [{ href: "/dashboard", label: "Overview", icon: "grid" }, { href: "/assistants", label: "AI employees", icon: "spark" }, { href: "/work", label: "Work", icon: "work" }, { href: "/knowledge", label: "Knowledge", icon: "book" }, { href: "/conversations", label: "Conversations", icon: "chat" }, { href: "/analytics", label: "Analytics", icon: "chart" }] as const;
function NavIcon({ name }: { name: (typeof navigationItems)[number]["icon"] }) { const paths = { grid: <><rect x="3" y="3" width="7" height="7" rx="1" /><rect x="14" y="3" width="7" height="7" rx="1" /><rect x="3" y="14" width="7" height="7" rx="1" /><rect x="14" y="14" width="7" height="7" rx="1" /></>, spark: <path d="m12 2 1.9 6.1L20 10l-6.1 1.9L12 18l-1.9-6.1L4 10l6.1-1.9L12 2Z" />, work: <><rect x="3" y="7" width="18" height="13" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12h18M10 12v2h4v-2"/></>, book: <><path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H11v16H6.5A2.5 2.5 0 0 0 4 21V5.5Z" /><path d="M20 5.5A2.5 2.5 0 0 0 17.5 3H13v16h4.5A2.5 2.5 0 0 1 20 21V5.5Z" /></>, chat: <path d="M20 11.5a7.5 7.5 0 0 1-8 7.5 8.8 8.8 0 0 1-3.6-.8L4 20l1.4-3.7A7.1 7.1 0 0 1 4 11.5 7.5 7.5 0 0 1 12 4a7.5 7.5 0 0 1 8 7.5Z" />, chart: <><path d="M4 20V10" /><path d="M10 20V4" /><path d="M16 20v-7" /><path d="M22 20H2" /></> }; return <svg className={styles.navIcon} aria-hidden="true" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8">{paths[name]}</svg>; }
export function WorkspaceShell({ children }: WorkspaceShellProps) { const pathname = usePathname(); const router = useRouter(); const { session, loading, signOut } = useSession(); useEffect(() => { if (!loading && !session) router.replace("/sign-in"); }, [loading, router, session]); if (loading || !session) return <div style={{ alignItems: "center", color: "var(--muted)", display: "flex", height: "100vh", justifyContent: "center" }}>Loading your workspace…</div>; const initials = session.user.full_name.split(" ").map((word) => word[0]).join("").slice(0, 2).toUpperCase(); return <div className={styles.shell}><aside className={styles.sidebar}><Link className={styles.brand} href="/dashboard"><Image className={styles.brandMark} src="/brand/eunia-nia-mark.png" alt="" width={32} height={32} priority /><span>EUNIA</span></Link><div className={styles.workspaceLabel}>WORKSPACE</div><nav className={styles.navigation}>{navigationItems.map((item) => <Link className={`${styles.navigationItem} ${pathname.startsWith(item.href) ? styles.active : ""}`} href={item.href} key={item.href}><NavIcon name={item.icon} />{item.label}</Link>)}</nav><div className={styles.sidebarBottom}><Link className={styles.settings} href="/settings"><span>⚙</span> Settings</Link><button className={styles.organization} style={{ background: "transparent", border: 0, color: "inherit", cursor: "pointer", textAlign: "left", width: "100%" }} type="button" onClick={() => { signOut(); router.replace("/sign-in"); }} title="Sign out"><span className={styles.companyBadge}>{initials}</span><div><strong>{session.workspace.name}</strong><span>Sign out</span></div><span className={styles.chevron}>⌄</span></button></div></aside><div className={styles.contentArea}><header className={styles.header}><div className={styles.breadcrumb}><span>{session.workspace.name}</span><span>/</span><strong>{navigationItems.find((item) => pathname.startsWith(item.href))?.label ?? "Workspace"}</strong></div><div className={styles.headerActions}><button className={styles.helpButton} type="button" aria-label="Help">?</button><button className={styles.profileButton} type="button">{initials}</button></div></header><main className={styles.content}>{children}</main></div></div>; }
