"use client";
import Link from "next/link";
import Image from "next/image";
import { FormEvent, useState } from "react";
import { useRouter } from "next/navigation";
import { signIn } from "@/lib/eunia-api";
import { useSession, userForToken, workspaceForToken } from "@/components/session-provider";
import styles from "../auth.module.css";
export default function SignInPage() { const router = useRouter(); const { startSession } = useSession(); const [error, setError] = useState(""); const [pending, setPending] = useState(false); const [visible, setVisible] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); const form = new FormData(event.currentTarget); try { const token = await signIn({ email: String(form.get("email")), password: String(form.get("password")) }); const [workspace, user] = await Promise.all([workspaceForToken(token.access_token), userForToken(token.access_token)]); startSession(token.access_token, workspace, user); router.replace("/dashboard"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to sign in."); } finally { setPending(false); } } return <main className={styles.page}><section className={styles.card}><Link className={styles.brand} href="/"><Image className={styles.brandMark} src="/brand/eunia-nia-mark.png" alt="" width={28} height={28} priority />EUNIA</Link><p className={styles.eyebrow}>WELCOME BACK</p><h1>Sign in to your workspace</h1><p className={styles.subtitle}>Use the account your organisation created for you.</p><form onSubmit={submit}><label>Email<input name="email" type="email" required autoComplete="email" /></label><label>Password<span className={styles.passwordField}><input name="password" type={visible ? "text" : "password"} required autoComplete="current-password" /><button className={styles.reveal} type="button" onClick={() => setVisible(!visible)}>{visible ? "Hide" : "Show"}</button></span></label><Link className={styles.forgot} href="/forgot-password">Forgot password?</Link>{error && <p className={styles.error}>{error}</p>}<button disabled={pending} type="submit">{pending ? "Signing in…" : "Sign in"}</button></form><p className={styles.switch}>New to EUNIA? <Link href="/sign-up">Create your workspace</Link></p></section></main>; }
