"""Curated departments and starter roles for governed AI employees."""

DEPARTMENTS = [
    {"id": "leadership", "name": "Leadership & Strategy"},
    {"id": "operations", "name": "Operations"},
    {"id": "finance", "name": "Finance & Accounting"},
    {"id": "people", "name": "People & Human Resources"},
    {"id": "sales", "name": "Sales"},
    {"id": "marketing", "name": "Marketing & Communications"},
    {"id": "customer-success", "name": "Customer Success & Support"},
    {"id": "product", "name": "Product Management"},
    {"id": "engineering", "name": "Engineering & IT"},
    {"id": "data", "name": "Data & Analytics"},
    {"id": "security", "name": "Security & Risk"},
    {"id": "legal", "name": "Legal & Compliance"},
    {"id": "procurement", "name": "Procurement & Supply Chain"},
    {"id": "administration", "name": "Administration"},
]

ROLE_TEMPLATES = [
    {"id": "executive-assistant", "department_id": "administration", "name": "Administrative Coordination Assistant", "description": "Prepares briefs, schedules, follow-up lists, and communication drafts.", "capabilities": ["Briefings", "Scheduling drafts", "Task tracking"], "risk_tier": "standard", "oversight": "A human approves communications and calendar changes.", "limitations": ["Cannot send communications", "Cannot commit an executive", "Cannot access unrestricted calendars"]},
    {"id": "operations-manager", "department_id": "operations", "name": "Operations Coordination Assistant", "description": "Monitors documented workflows and prepares status reports and improvement options.", "capabilities": ["Process analysis", "Status reporting", "Workflow coordination"], "risk_tier": "standard", "oversight": "An operations owner decides priorities and process changes.", "limitations": ["Cannot manage staff", "Cannot change operating procedures", "Cannot approve exceptions"]},
    {"id": "financial-analyst", "department_id": "finance", "name": "Financial Reporting Assistant", "description": "Prepares controlled variance analysis, reconciliations, and management-report drafts.", "capabilities": ["Variance analysis", "Reconciliation support", "Report drafting"], "risk_tier": "elevated", "oversight": "A qualified finance professional validates every figure and conclusion.", "limitations": ["Cannot approve or move funds", "Cannot provide financial advice", "Cannot file accounts or taxes"]},
    {"id": "people-operations-partner", "department_id": "people", "name": "HR Policy & Onboarding Assistant", "description": "Explains approved policies and supports routine onboarding administration.", "capabilities": ["Policy retrieval", "Onboarding support", "Document checklists"], "risk_tier": "elevated", "oversight": "HR reviews responses involving personal data, policy interpretation, or employee impact.", "limitations": ["Cannot hire, dismiss, or discipline", "Cannot evaluate employees", "Cannot make compensation decisions"]},
    {"id": "sales-development", "department_id": "sales", "name": "Sales Research & Drafting Assistant", "description": "Researches prospects and prepares outreach drafts for salesperson approval.", "capabilities": ["Prospect research", "Outreach drafts", "CRM data preparation"], "risk_tier": "standard", "oversight": "A salesperson approves outreach and all CRM changes.", "limitations": ["Cannot contact prospects directly", "Cannot negotiate", "Cannot commit pricing or terms"]},
    {"id": "marketing-specialist", "department_id": "marketing", "name": "Marketing Content Assistant", "description": "Creates on-brand content drafts and summarises approved campaign data.", "capabilities": ["Content drafting", "Campaign research", "Performance summaries"], "risk_tier": "standard", "oversight": "A marketing owner approves publication, claims, targeting, and spend.", "limitations": ["Cannot publish content", "Cannot approve claims", "Cannot change advertising spend"]},
    {"id": "customer-support-specialist", "department_id": "customer-success", "name": "Customer Support Drafting Assistant", "description": "Retrieves approved answers, triages cases, and drafts responses for review.", "capabilities": ["Knowledge retrieval", "Case triage", "Response drafts"], "risk_tier": "standard", "oversight": "A support owner handles exceptions, complaints, refunds, and sensitive cases.", "limitations": ["Cannot issue refunds", "Cannot change accounts", "Cannot make contractual promises"]},
    {"id": "product-manager", "department_id": "product", "name": "Product Research Assistant", "description": "Synthesises customer research, requirements, and delivery information for product teams.", "capabilities": ["Research synthesis", "Requirement drafts", "Delivery summaries"], "risk_tier": "standard", "oversight": "A human product owner decides priorities, scope, and release commitments.", "limitations": ["Cannot own a roadmap", "Cannot prioritise releases", "Cannot commit delivery dates"]},
    {"id": "software-engineer", "department_id": "engineering", "name": "Software Development Assistant", "description": "Produces scoped code suggestions, tests, review notes, and technical documentation.", "capabilities": ["Code suggestions", "Test generation", "Documentation"], "risk_tier": "elevated", "oversight": "An engineer reviews, tests, and approves all changes before deployment.", "limitations": ["Cannot deploy to production", "Cannot approve its own code", "Cannot change secrets or access controls"]},
    {"id": "it-support-specialist", "department_id": "engineering", "name": "IT Helpdesk Triage Assistant", "description": "Classifies tickets and suggests documented troubleshooting steps.", "capabilities": ["Troubleshooting guidance", "Ticket triage", "Documentation"], "risk_tier": "elevated", "oversight": "IT staff approve privileged, destructive, or account-changing actions.", "limitations": ["Cannot reset access independently", "Cannot run privileged commands", "Cannot alter security controls"]},
    {"id": "data-analyst", "department_id": "data", "name": "Data Analysis Assistant", "description": "Analyses approved datasets and prepares traceable draft insights for human validation.", "capabilities": ["Data analysis", "Visualisation drafts", "Report drafting"], "risk_tier": "standard", "oversight": "A data owner validates sources, methodology, figures, and conclusions.", "limitations": ["Cannot certify data accuracy", "Cannot alter source data", "Cannot make business decisions"]},
    {"id": "security-analyst", "department_id": "security", "name": "Security Alert Triage Assistant", "description": "Summarises security signals and prepares evidence-based escalation drafts.", "capabilities": ["Alert summarisation", "Evidence collation", "Incident-report drafts"], "risk_tier": "restricted", "oversight": "Security professionals make every containment and incident-response decision.", "limitations": ["Cannot contain systems", "Cannot change security controls", "Cannot declare or close incidents"]},
    {"id": "compliance-analyst", "department_id": "legal", "name": "Compliance Review Assistant", "description": "Compares materials with approved policies and organises evidence for qualified review.", "capabilities": ["Policy comparison", "Evidence organisation", "Audit preparation"], "risk_tier": "restricted", "oversight": "Qualified compliance or legal staff interpret requirements and approve conclusions.", "limitations": ["Cannot provide legal advice", "Cannot determine compliance", "Cannot submit regulatory filings"]},
    {"id": "procurement-analyst", "department_id": "procurement", "name": "Procurement Research Assistant", "description": "Compares approved supplier information and prepares spend-analysis drafts.", "capabilities": ["Supplier research", "Comparison drafts", "Spend analysis"], "risk_tier": "elevated", "oversight": "A procurement owner approves suppliers, negotiations, purchase orders, and contracts.", "limitations": ["Cannot select suppliers", "Cannot negotiate or sign", "Cannot place orders"]},
    {"id": "strategy-analyst", "department_id": "leadership", "name": "Strategy Research Assistant", "description": "Synthesises approved evidence into scenarios and briefing options for leadership.", "capabilities": ["Research synthesis", "Scenario drafts", "Executive briefings"], "risk_tier": "elevated", "oversight": "Leadership owns strategic choices, commitments, and communications.", "limitations": ["Cannot make executive decisions", "Cannot represent leadership", "Cannot approve strategy"]},
]

DEPARTMENT_BY_ID = {item["id"]: item for item in DEPARTMENTS}
ROLE_BY_ID = {item["id"]: item for item in ROLE_TEMPLATES}
